config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "/home/about" => "homes#about", as: "about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, length: { in: 1..200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_one_attached :profile_image
         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy

           validates :name, length: { in: 2..20 }, uniqueness: true
           validates :introduction, length: { maximum: 50 }

  GUEST_USER_EMAIL = "guest@example.com"

    def self.guest
      find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "guestuser"
      end
    end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]



  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
    redirect_to @book
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end


  def show
    @books = Book.find(params[:id])
    @book = Book.new
    @user = @books.user
    @users = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book_favorite = Favorite.new(user_id: current_user.id, book_id: params[:book_id])
    @book_favorite.save
    redirect_to book_path(params[:book_id])
  end

  def destroy
    @book_favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
    @book_favorite.destroy
    redirect_to book_path(params[:book_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]


  def index
    @users = User.all
    @user = User.new
    @book = current_user
    @books =Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.email == "guest@example.com"
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
<div class="form-group">
<label for="book_title">Title</label><br>
<%= f.text_field :title %>
</div>

<div class="form-group">
<label for="book_opinion">Opinion</label><br>
<%= f.text_area :body %>
</div>
<div class="form-group">
<%= f.submit 'Update Book', class:"btn btn-success" %>
</div>
<% end %>

<%= link_to 'Show', book_path(@book) %>
|
<%= link_to 'Back', books_path(@books) %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<h2>User info</h2>

<%= image_tag @user.get_profile_image(100,100) %>

<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= @user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
<%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog" style="color: #999da3;"></i>
<% end %>
</div>


<h2>New book</h2>
  <%= form_with model: @book do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
      </td>
      <td>
        <%= link_to book_path(book) do %>
        <%= book.title %>
        <% end %>
      </td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>
  </div>
  </div>
</div>
</main>

app/views/books/show.html.erb
<%= flash[:notice] %>

<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<h2>User info</h2>

<%= image_tag @user.get_profile_image(100,100) %>


<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= @user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
<%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog" style="color: #999da3;"></i>
<% end %>
</div>

<h2>New book</h2>
  <%= form_with model: @book do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(@books.user.id) do %>
        <%= image_tag @books.user.get_profile_image(100,100) %><br>
        <%= @books.user.name %>
        <% end %>
      </td>
      <td>
        <%= link_to book_path(@books.id) do %>
        <%= @books.title %>
        <% end %>
      </td>
      <td><%= @books.body %></td>
      <td>
        <% if @book.favorited_by?(current_user) %>
          <%= link_to book_favorites_path(book.id), method: :delete do %>
            ♥<%= @book.favorites.count %> いいね
          <% end %>
        <% else %>
          <%= link_to book_favorites_path(@books.id), method: :post do %>
            ♡<%= @books.favorites.count %> いいね
          <% end %>
        <% end %>
      </td>
      <% if @books.user == current_user %>
        <td><%= link_to "Edit", edit_book_path(@books.id), class:"btn btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", book_path(@books.id), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-sm btn-danger" %></td>
      <% end %>
    </tr>
  </tbody>
</table>
  </div>
  </div>
</div>
</main>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i></svg><strong>Bookers</strong> !!</h1>
        <p>In <i class="fas fa-book"></i></svg><strong>Bookers</strong>,</p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
          </div>
          <div class="row">
            <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
          </div>
          <div class="row">
            <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <%= link_to 'Bookers', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user) do %>
                <i class="fas fa-home" style="color: #ffffff;"></i> <span class="text-light">Home</span>
                <% end %>
              </li>
              <li>
                <%= link_to  users_path do %>
                <i class="fas fa-users" style="color: #ffffff;"></i>  <span class="text-light">Users</span>
                <% end %>
              </li>
              <li>
                <%= link_to books_path do %>
                <i class="fas fa-book-open" style="color: #ffffff;"></i>  <span class="text-light">Books</span>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt" style="color: #ffffff;"></i> <span class="text-light">Log out</span>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path do %>
                <i class="fas fa-home" style="color: #ffffff;"></i> <span class="text-light">Home</span>
                <% end %>
              </li>
              <li>
                <%= link_to about_path do %>
                <i class="fas fa-link" style="color: #ffffff;"></i> <span class="text-light">About</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus" style="color: #ffffff;"></i>  <span class="text-light">Sign up</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                <i class="fas fa-sign-in-alt" style="color: #ffffff;"></i>  <span class="text-light">Log in</span>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>

<% if @user.errors.any? %>
  <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @user do |f| %>
<div class="form-group">
  <label for="user_Name">Name</label><br>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
</div>
<div class="form-group">
  <label for="user_Image">Image</label><br>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
</div>
<div class="form-group">
  <label for="user_Introduction">Introduction</label><br>
  <%= f.text_area :introduction %>
</div>
<div class="form-group">
  <%= f.submit "Update User", class:"btn btn-secondary" %>
</div>
<% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<h2>User info</h2>

<div>
  <%= image_tag @book.get_profile_image(100,100) %>
</div>

<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= @book.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @book.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
<%= link_to edit_user_path(@book.id), class:"btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog" style="color: #999da3;"></i>
<% end %>
</div>

<h2>New book</h2>
  <%= form_with model: @books do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
  </div>
  </div>
</div>
</main>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<h2>User info</h2>


<div>
  <%= image_tag @user.get_profile_image(100,100) %>
</div>

<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= @user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
<%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog" style="color: #999da3;"></i>
<% end %>
</div>

<h2>New book</h2>
  <%= form_with model: @book do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(@user.id) do %>
        <%= image_tag @user.get_profile_image(100,100) %>
        <% end %>
        </td>
      <td>
        <%= link_to book_path(book) do %>
        <%= book.title %>
        <% end %>
        </td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
  </div>
</div>
</main>